### ISSUE TITLE
BUG 版本：Mihomo Meta alpha-9bd70e1 android arm64 with go1.20.13 Wed Jan 24 09:53:25 UTC 2024 Use tags: with_gvisor

### ISSUE THREAD

**Issue by Chuhe2399** [MetaCubeX/mihomo#1014]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-9bd70e1 android arm64 with go1.20.13 Wed Jan 24 09:53:25 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
mixed-port: 8888
tproxy-port: 7893
allow-lan: true
bind-address: "*" 
find-process-mode: strict
mode: rule
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: true
geo-update-interval: 24
global-ua: clash.meta
geodata-mode: true
geodata-loader: standard
geosite-matcher: succinct
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
external-ui: Dashboard
global-client-fingerprint: chrome
keep-alive-interval: 30
tcp-concurrent: true
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
  
tun: 
  enable: true
  device: Tun
  stack: Mixed
  dns-hijack: ['any:53']
  auto-route: true
  auto-detect-interface: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
  
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fallback-filter: {geoip: true, geoip-code: CN, geosite: ['!CN', 'GFW', 'GREATFIRE'], ipcidr: ['240.0.0.0/4'], domain: ['+.google.com', '+.facebook.com', '+.youtube.com']}
  fake-ip-filter: ['*.lan', 'connect.rom.miui.com', 'www.msftconnecttest.com', 'localhost.ptlogin2.qq.com', 'xbox.*.microsoft.com', '+.xboxlive.com', '+.bilivideo.com']
  default-nameserver: ['tls://223.5.5.5', 'tls://8.8.8.8', 'tls://119.29.29.29', 'tls://1.1.1.1']
  proxy-server-nameserver: ['tls://223.5.5.5', 'tls://8.8.8.8', 'tls://119.29.29.29', 'tls://1.1.1.1']
  nameserver: ['tls://223.5.5.5#🎯国内选择', 'tls://119.29.29.29#🎯国内选择']
  fallback: ['tls://8.8.8.8#🚀国外选择', 'tls://1.1.1.1#🚀国外选择']
```

### Mihomo log

```shell
time="2024-01-29T11:47:18.523938195Z" level=info msg="Start initial configuration in progress"
time="2024-01-29T11:47:18.524440643Z" level=warning msg="Skip start health check timer due to it's started"
time="2024-01-29T11:47:18.524492726Z" level=warning msg="Skip start health check timer due to it's started"
time="2024-01-29T11:47:18.524571893Z" level=info msg="Geodata Loader mode: standard"
time="2024-01-29T11:47:18.524595174Z" level=info msg="Geosite Matcher implementation: succinct"
time="2024-01-29T11:47:18.810364497Z" level=info msg="Start initial GeoSite rule chinamobile => DIRECT, records: 16"
time="2024-01-29T11:47:18.845440643Z" level=info msg="Start initial GeoSite rule chinaunicom => DIRECT, records: 11"
time="2024-01-29T11:47:18.883129028Z" level=info msg="Start initial GeoSite rule chinatelecom => DIRECT, records: 10"
time="2024-01-29T11:47:18.918251372Z" level=info msg="Start initial GeoSite rule private => DIRECT, records: 137"
time="2024-01-29T11:47:18.958345383Z" level=info msg="Start initial GeoSite rule jd => 🎯国内选择, records: 237"
time="2024-01-29T11:47:18.995523403Z" level=info msg="Start initial GeoSite rule didi => 🎯国内选择, records: 7"
time="2024-01-29T11:47:19.033213195Z" level=info msg="Start initial GeoSite rule abc => 🎯国内选择, records: 3"
time="2024-01-29T11:47:19.077362883Z" level=info msg="Start initial GeoSite rule boc => 🎯国内选择, records: 20"
time="2024-01-29T11:47:19.110546685Z" level=info msg="Start initial GeoSite rule ccb => 🎯国内选择, records: 16"
time="2024-01-29T11:47:19.145414966Z" level=info msg="Start initial GeoSite rule icbc => 🎯国内选择, records: 58"
time="2024-01-29T11:47:19.179612778Z" level=info msg="Start initial GeoSite rule cmb => 🎯国内选择, records: 21"
time="2024-01-29T11:47:19.211080851Z" level=info msg="Start initial GeoSite rule iqiyi => 🎯国内选择, records: 27"
time="2024-01-29T11:47:19.257022049Z" level=info msg="Start initial GeoSite rule huya => 🎯国内选择, records: 2"
time="2024-01-29T11:47:19.289689966Z" level=info msg="Start initial GeoSite rule csdn => 🎯国内选择, records: 15"
time="2024-01-29T11:47:19.328061007Z" level=info msg="Start initial GeoSite rule oppo => 🎯国内选择, records: 20"
time="2024-01-29T11:47:19.359950487Z" level=info msg="Start initial GeoSite rule 4399 => 🎯国内选择, records: 55"
time="2024-01-29T11:47:19.396136216Z" level=info msg="Start initial GeoSite rule baidu => 🎯国内选择, records: 194"
time="2024-01-29T11:47:19.433587674Z" level=info msg="Start initial GeoSite rule zhihu => 🎯国内选择, records: 2"
time="2024-01-29T11:47:19.468706164Z" level=info msg="Start initial GeoSite rule bilibili => 🎯国内选择, records: 50"
time="2024-01-29T11:47:19.503583195Z" level=info msg="Start initial GeoSite rule aliyun => 🎯国内选择, records: 62"
time="2024-01-29T11:47:19.543822674Z" level=info msg="Start initial GeoSite rule xiaomi => 🎯国内选择, records: 11"
time="2024-01-29T11:47:19.579793455Z" level=info msg="Start initial GeoSite rule alibaba => 🎯国内选择, records: 338"
time="2024-01-29T11:47:19.616157153Z" level=info msg="Start initial GeoSite rule huawei => 🎯国内选择, records: 275"
time="2024-01-29T11:47:19.64876757Z" level=info msg="Start initial GeoSite rule douban => 🎯国内选择, records: 3"
time="2024-01-29T11:47:19.686246997Z" level=info msg="Start initial GeoSite rule tencent => 🎯国内选择, records: 457"
time="2024-01-29T11:47:19.719163716Z" level=info msg="Start initial GeoSite rule dingtalk => 🎯国内选择, records: 8"
time="2024-01-29T11:47:19.754808195Z" level=info msg="Start initial GeoSite rule meituan => 🎯国内选择, records: 7"
time="2024-01-29T11:47:19.792553768Z" level=info msg="Start initial GeoSite rule chaoxing => 🎯国内选择, records: 32"
time="2024-01-29T11:47:19.82429882Z" level=info msg="Start initial GeoSite rule apple-cn => 🎯国内选择, records: 140"
time="2024-01-29T11:47:19.864219236Z" level=info msg="Start initial GeoSite rule apple@cn => 🎯国内选择, records: 256"
time="2024-01-29T11:47:19.894513091Z" level=info msg="Start initial GeoSite rule icloud@cn => 🎯国内选择, records: 6"
time="2024-01-29T11:47:19.929983195Z" level=info msg="Start initial GeoSite rule alibabacloud => 🎯国内选择, records: 8"
time="2024-01-29T11:47:19.964394393Z" level=info msg="Start initial GeoSite rule chinatelecom => 🎯国内选择, records: 10"
time="2024-01-29T11:47:19.998811476Z" level=info msg="Start initial GeoSite rule 58tongcheng => 🎯国内选择, records: 36"
time="2024-01-29T11:47:20.032735903Z" level=info msg="Start initial GeoSite rule microsoft@cn => 🎯国内选择, records: 137"
time="2024-01-29T11:47:20.070340799Z" level=info msg="Start initial GeoSite rule tencent-games => 🎯国内选择, records: 86"
time="2024-01-29T11:47:20.11651158Z" level=info msg="Start initial GeoSite rule geolocation-cn => 🎯国内选择, records: 4625"
time="2024-01-29T11:47:20.348744757Z" level=info msg="Start initial GeoSite rule CN => 🎯国内选择, records: 67075"
time="2024-01-29T11:47:20.378863715Z" level=info msg="Start initial GeoSite rule bing => 🚀国外选择, records: 32"
time="2024-01-29T11:47:20.410586632Z" level=info msg="Start initial GeoSite rule twitter => 🚀国外选择, records: 23"
time="2024-01-29T11:47:20.445398455Z" level=info msg="Start initial GeoSite rule Discord => 🚀国外选择, records: 27"
time="2024-01-29T11:47:20.48074684Z" level=info msg="Start initial GeoSite rule telegram => 🚀国外选择, records: 19"
time="2024-01-29T11:47:20.513456059Z" level=info msg="Start initial GeoSite rule facebook => 🚀国外选择, records: 395"
time="2024-01-29T11:47:20.549707778Z" level=info msg="Start initial GeoSite rule whatsapp => 🚀国外选择, records: 11"
time="2024-01-29T11:47:20.583797101Z" level=info msg="Start initial GeoSite rule googlefcm => 🚀国外选择, records: 9"
time="2024-01-29T11:47:20.617022361Z" level=info msg="Start initial GeoSite rule 2kgames => 🚀国外选择, records: 4"
time="2024-01-29T11:47:20.641743507Z" level=info msg="Start initial GeoSite rule bilibili-game => 🚀国外选择, records: 6"
time="2024-01-29T11:47:20.677030746Z" level=info msg="Start initial GeoSite rule blizzard => 🚀国外选择, records: 23"
time="2024-01-29T11:47:20.706161163Z" level=info msg="Start initial GeoSite rule curseforge => 🚀国外选择, records: 2"
time="2024-01-29T11:47:20.745014705Z" level=info msg="Start initial GeoSite rule cygames => 🚀国外选择, records: 5"
time="2024-01-29T11:47:20.77827809Z" level=info msg="Start initial GeoSite rule ea => 🚀国外选择, records: 165"
time="2024-01-29T11:47:20.815732465Z" level=info msg="Start initial GeoSite rule epicgames => 🚀国外选择, records: 17"
time="2024-01-29T11:47:20.849048194Z" level=info msg="Start initial GeoSite rule garena => 🚀国外选择, records: 16"
time="2024-01-29T11:47:20.889849913Z" level=info msg="Start initial GeoSite rule gog => 🚀国外选择, records: 11"
time="2024-01-29T11:47:20.923463298Z" level=info msg="Start initial GeoSite rule illusion => 🚀国外选择, records: 2"
time="2024-01-29T11:47:20.956454028Z" level=info msg="Start initial GeoSite rule lowiro => 🚀国外选择, records: 1"
time="2024-01-29T11:47:20.987669548Z" level=info msg="Start initial GeoSite rule mihoyo => 🚀国外选择, records: 21"
time="2024-01-29T11:47:21.022132465Z" level=info msg="Start initial GeoSite rule nintendo => 🚀国外选择, records: 124"
time="2024-01-29T11:47:21.056714809Z" level=info msg="Start initial GeoSite rule op => 🚀国外选择, records: 2"
time="2024-01-29T11:47:21.089108142Z" level=info msg="Start initial GeoSite rule pandanet => 🚀国外选择, records: 2"
time="2024-01-29T11:47:21.12361658Z" level=info msg="Start initial GeoSite rule pinkcore => 🚀国外选择, records: 2"
time="2024-01-29T11:47:21.158536475Z" level=info msg="Start initial GeoSite rule playstation => 🚀国外选择, records: 4"
time="2024-01-29T11:47:21.19214158Z" level=info msg="Start initial GeoSite rule purikonejp => 🚀国外选择, records: 3"
time="2024-01-29T11:47:21.224079965Z" level=info msg="Start initial GeoSite rule riot => 🚀国外选择, records: 54"
time="2024-01-29T11:47:21.258076267Z" level=info msg="Start initial GeoSite rule rockstar => 🚀国外选择, records: 5"
time="2024-01-29T11:47:21.294161007Z" level=info msg="Start initial GeoSite rule steam => 🚀国外选择, records: 48"
time="2024-01-29T11:47:21.325881944Z" level=info msg="Start initial GeoSite rule steamunlocked => 🚀国外选择, records: 1"
time="2024-01-29T11:47:21.364790746Z" level=info msg="Start initial GeoSite rule tencent-games => 🚀国外选择, records: 86"
time="2024-01-29T11:47:21.397995277Z" level=info msg="Start initial GeoSite rule ubisoft => 🚀国外选择, records: 8"
time="2024-01-29T11:47:21.434427569Z" level=info msg="Start initial GeoSite rule xbox => 🚀国外选择, records: 38"
time="2024-01-29T11:47:21.470299288Z" level=info msg="Start initial GeoSite rule ynoproject => 🚀国外选择, records: 1"
time="2024-01-29T11:47:21.508011892Z" level=info msg="Start initial GeoSite rule category-games => 🚀国外选择, records: 681"
time="2024-01-29T11:47:21.543317517Z" level=info msg="Start initial GeoSite rule bbc => 🚀国外选择, records: 27"
time="2024-01-29T11:47:21.579350329Z" level=info msg="Start initial GeoSite rule tiktok => 🚀国外选择, records: 12"
time="2024-01-29T11:47:21.612411892Z" level=info msg="Start initial GeoSite rule netflix => 🚀国外选择, records: 25"
time="2024-01-29T11:47:21.647567569Z" level=info msg="Start initial GeoSite rule youtube => 🚀国外选择, records: 176"
time="2024-01-29T11:47:21.680038246Z" level=info msg="Start initial GeoSite rule paypal => 🚀国外选择, records: 245"
time="2024-01-29T11:47:21.715671996Z" level=info msg="Start initial GeoSite rule openai => 🚀国外选择, records: 11"
time="2024-01-29T11:47:21.74553059Z" level=info msg="Start initial GeoSite rule tor => 🚀国外选择, records: 3"
time="2024-01-29T11:47:21.781178767Z" level=info msg="Start initial GeoSite rule aws => 🚀国外选择, records: 64"
time="2024-01-29T11:47:21.814853767Z" level=info msg="Start initial GeoSite rule pixiv => 🚀国外选择, records: 8"
time="2024-01-29T11:47:21.847903975Z" level=info msg="Start initial GeoSite rule azure => 🚀国外选择, records: 112"
time="2024-01-29T11:47:21.88296184Z" level=info msg="Start initial GeoSite rule nginx => 🚀国外选择, records: 2"
time="2024-01-29T11:47:21.919038819Z" level=info msg="Start initial GeoSite rule adobe => 🚀国外选择, records: 263"
time="2024-01-29T11:47:21.952045642Z" level=info msg="Start initial GeoSite rule taptap => 🚀国外选择, records: 6"
time="2024-01-29T11:47:21.982892777Z" level=info msg="Start initial GeoSite rule github => 🚀国外选择, records: 27"
time="2024-01-29T11:47:22.022004548Z" level=info msg="Start initial GeoSite rule docker => 🚀国外选择, records: 3"
time="2024-01-29T11:47:22.051452517Z" level=info msg="Start initial GeoSite rule debian => 🚀国外选择, records: 2"
time="2024-01-29T11:47:22.087313975Z" level=info msg="Start initial GeoSite rule python => 🚀国外选择, records: 6"
time="2024-01-29T11:47:22.1193796Z" level=info msg="Start initial GeoSite rule termux => 🚀国外选择, records: 3"
time="2024-01-29T11:47:22.152829288Z" level=info msg="Start initial GeoSite rule adblock => 🚀国外选择, records: 1"
time="2024-01-29T11:47:22.185655017Z" level=info msg="Start initial GeoSite rule openwrt => 🚀国外选择, records: 2"
time="2024-01-29T11:47:22.221735069Z" level=info msg="Start initial GeoSite rule cloudflare => 🚀国外选择, records: 50"
time="2024-01-29T11:47:22.255400121Z" level=info msg="Start initial GeoSite rule adblockplus => 🚀国外选择, records: 1"
time="2024-01-29T11:47:22.286315121Z" level=info msg="Start initial GeoSite rule google => 🚀国外选择, records: 1082"
time="2024-01-29T11:47:22.321237673Z" level=info msg="Start initial GeoSite rule microsoft => 🚀国外选择, records: 626"
time="2024-01-29T11:47:22.404969079Z" level=info msg="Start initial GeoSite rule geolocation-!cn => 🚀国外选择, records: 19355"
time="2024-01-29T11:47:22.686033246Z" level=info msg="Start initial GeoIP rule private => DIRECT, records: 18"
time="2024-01-29T11:47:22.834662048Z" level=info msg="Start initial GeoIP rule CN => 🎯国内选择, records: 10812"
time="2024-01-29T11:47:22.957852933Z" level=info msg="Start initial GeoIP rule twitter => 🚀国外选择, records: 21"
time="2024-01-29T11:47:23.064902881Z" level=info msg="Start initial GeoIP rule telegram => 🚀国外选择, records: 12"
time="2024-01-29T11:47:23.203893818Z" level=info msg="Start initial GeoIP rule facebook => 🚀国外选择, records: 94"
time="2024-01-29T11:47:23.333194079Z" level=info msg="Start initial GeoIP rule netflix => 🚀国外选择, records: 18"
time="2024-01-29T11:47:23.473840016Z" level=info msg="Start initial GeoIP rule fastly => 🚀国外选择, records: 47"
time="2024-01-29T11:47:23.621863975Z" level=info msg="Start initial GeoIP rule google => 🚀国外选择, records: 544"
time="2024-01-29T11:47:23.760583922Z" level=info msg="Start initial GeoIP rule cloudflare => 🚀国外选择, records: 625"
time="2024-01-29T11:47:23.890748818Z" level=info msg="Start initial GeoIP rule cloudfront => 🚀国外选择, records: 166"
time="2024-01-29T11:47:23.891027204Z" level=warning msg="replace fallback-filter.geosite with nameserver-policy, it will be removed in the future"
time="2024-01-29T11:47:24.096835954Z" level=info msg="Start initial GeoSite dns fallback filter `!CN`, records: 67075"
time="2024-01-29T11:47:24.143210329Z" level=info msg="Start initial GeoSite dns fallback filter `GFW`, records: 6087"
time="2024-01-29T11:47:24.177419026Z" level=info msg="Start initial GeoSite dns fallback filter `GREATFIRE`, records: 8"
time="2024-01-29T11:47:24.178075433Z" level=info msg="Initial configuration complete, total time: 5654ms"
time="2024-01-29T11:47:24.178977776Z" level=info msg="RESTful API listening at: [::]:9090"
time="2024-01-29T11:47:24.184101058Z" level=info msg="Sniffer is loaded and working"
time="2024-01-29T11:47:24.184116683Z" level=info msg="Use tcp concurrent"
time="2024-01-29T11:47:24.184252151Z" level=info msg="DNS server listening at: [::]:1053"
time="2024-01-29T11:47:24.184349391Z" level=info msg="TProxy server listening at: [::]:7893"
time="2024-01-29T11:47:24.184475068Z" level=info msg="Mixed(http+socks) proxy listening at: [::]:8888"
time="2024-01-29T11:47:24.185117828Z" level=warning msg="[TUN] default interface changed by monitor,  => wlan0"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58b4717290]

goroutine 1 [running]:
github.com/metacubex/gvisor/pkg/tcpip/link/channel.(*Endpoint).Attach(0x0, {0x0?, 0x0})
	github.com/metacubex/gvisor@v0.0.0-20231209122014-3e43224c7bbc/pkg/tcpip/link/channel/channel.go:209 +0x30
github.com/metacubex/sing-tun.(*Mixed).Close(0x4000418c80)
	github.com/metacubex/sing-tun@v0.2.0/stack_mixed.go:264 +0x30
github.com/sagernet/sing/common.Close({0x400337ca38?, 0x5, 0x400337cac8?})
	github.com/sagernet/sing@v0.3.0/common/cond.go:351 +0x8c
github.com/metacubex/mihomo/listener/sing_tun.(*Listener).Close(...)
	github.com/metacubex/mihomo/listener/sing_tun/server.go:334
github.com/metacubex/mihomo/listener/sing_tun.New.func1()
	github.com/metacubex/mihomo/listener/sing_tun/server.go:175 +0xd8
github.com/metacubex/mihomo/listener/sing_tun.New({0x1, {0x40002aa1a0, 0x3}, 0x2, {0x40002c6d60, 0x1, 0x1}, 0x1, 0x1, {0x58b6065de8, ...}, ...}, ...)
	github.com/metacubex/mihomo/listener/sing_tun/server.go:266 +0x1594
github.com/metacubex/mihomo/listener.ReCreateTun({0x1, {0x40002aa1a0, 0x3}, 0x2, {0x40002c6d60, 0x1, 0x1}, 0x1, 0x1, {0x58b6065de8, ...}, ...}, ...)
	github.com/metacubex/mihomo/listener/listener.go:534 +0x1a0
github.com/metacubex/mihomo/hub/executor.updateTun(0x400026aa00)
	github.com/metacubex/mihomo/hub/executor/executor.go:352 +0x78
github.com/metacubex/mihomo/hub/executor.ApplyConfig(0x40000ee6c0, 0xc0?)
	github.com/metacubex/mihomo/hub/executor/executor.go:103 +0x29c
github.com/metacubex/mihomo/hub.Parse({0x0, 0x0, 0x40?})
	github.com/metacubex/mihomo/hub/hub.go:50 +0x270
main.main()
	github.com/metacubex/mihomo/main.go:109 +0x66c
```

### Description

启动不了。
