### ISSUE TITLE
[Bug] ResolveInterface 会错误地跳过其他和 Meta tun 接口一样的设备，导致 interface-name 配置字段失效

### ISSUE THREAD

**Issue by james-curtis** [MetaCubeX/mihomo#1085]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.1

### What OS are you seeing the problem on?

macOS, Windows, Linux, OpenBSD/FreeBSD

### Mihomo config

```diff
log-level: debug

listeners:
  - name: mixed-in
    type: mixed
    port: 7892
    listen: 0.0.0.0
    udp: true
    proxy: dd

proxies:
  - name: dd
    type: direct
    udp: true
+    interface-name: "just to hit breakpoint"
```

### Mihomo log

```shell
PS C:\Users\Administrator\Downloads\mihomo-windows-amd64-v1.18.1> .\mihomo-windows-amd64.exe -m -d . -f .\meta.yml
time="2024-03-07T16:13:22.0274053+08:00" level=info msg="Start initial configuration in progress"
time="2024-03-07T16:13:22.0473284+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-03-07T16:13:22.0502955+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-03-07T16:13:22.0632923+08:00" level=info msg="Initial configuration complete, total time: 15ms"
time="2024-03-07T16:13:22.0642729+08:00" level=info msg="Sniffer is closed"
time="2024-03-07T16:13:22.069325+08:00" level=info msg="Mixed(http+socks)[mixed-in] proxy listening at: [::]:7892"
time="2024-03-07T16:13:22.0766837+08:00" level=info msg="Start initial Compatible provider default"
time="2024-03-07T16:13:30.6153533+08:00" level=warning msg="[TCP] dial dd [::1]:64043 --> ip.skk.moe:443 error: connect failed: interface not found\ninterface not found\nconnect failed: interface not found\ninterface not found"
```

### Description

[这一行代码](https://github.com/MetaCubeX/mihomo/blob/a034421a58674dd80399702de657250910bfeac3/component/iface/iface.go#L42C1-L42C10)除了把 Meta tun 接口过滤掉了，也会把 Google One VPN 同类的接口也过滤掉

一样的 Flag
![image](https://github.com/MetaCubeX/mihomo/assets/49338067/2a59ea7c-b260-47eb-a7ef-251c3fdfce74)

**Comment by james-curtis** [comment]
对文件进行如下修改

/component/iface/iface.go
```diff
func ResolveInterface(name string) (*Interface, error) {
	value, err, _ := interfaces.Do(func() (map[string]*Interface, error) {
		ifaces, err := net.Interfaces()
		if err != nil {
			return nil, err
		}

		r := map[string]*Interface{}

		for _, iface := range ifaces {
			addrs, err := iface.Addrs()
			if err != nil {
				continue
			}
			// if not available device like Meta, dummy0, docker0, etc.
			if (iface.Flags&net.FlagMulticast == 0) || (iface.Flags&net.FlagPointToPoint != 0) || (iface.Flags&net.FlagRunning == 0) {
				continue
			}

			ipNets := make([]netip.Prefix, 0, len(addrs))
			for _, addr := range addrs {
				ipNet := addr.(*net.IPNet)
				ip, _ := netip.AddrFromSlice(ipNet.IP)

				//unavailable IPv6 Address
				if ip.Is6() && strings.HasPrefix(ip.String(), "fe80") {
					continue
				}

				ones, bits := ipNet.Mask.Size()
				if bits == 32 {
					ip = ip.Unmap()
				}

				pf := netip.PrefixFrom(ip, ones)
				ipNets = append(ipNets, pf)
			}

			r[iface.Name] = &Interface{
				Index:        iface.Index,
				Name:         iface.Name,
				Addrs:        ipNets,
				HardwareAddr: iface.HardwareAddr,
			}
		}

		return r, nil
	})
	if err != nil {
		return nil, err
	}

+	fmt.Println(value)
	ifaces := value
	iface, ok := ifaces[name]
+	fmt.Println(name)
	if !ok {
		return nil, ErrIfaceNotFound
	}

	return iface, nil
}
```

log
```
PS C:\Users\Administrator\Downloads\mihomo-windows-amd64-v1.18.1> .\main.exe -m -d . -f .\meta.yml
time="2024-03-07T16:51:08.93236+08:00" level=info msg="Start initial configuration in progress"
time="2024-03-07T16:51:08.948815+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-03-07T16:51:08.9508113+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-03-07T16:51:08.9618459+08:00" level=info msg="Initial configuration complete, total time: 14ms"
time="2024-03-07T16:51:08.9628573+08:00" level=info msg="Sniffer is closed"
time="2024-03-07T16:51:08.968831+08:00" level=info msg="Mixed(http+socks)[mixed-in] proxy listening at: [::]:7892"
time="2024-03-07T16:51:08.9769779+08:00" level=info msg="Start initial Compatible provider default"
time="2024-03-07T16:51:16.5076592+08:00" level=warning msg="[TCP] dial dd [::1]:64981 --> ip.skk.moe:443 error: dns resolve failed: lookup ip.skk.moe: i/o timeout"
map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]
VPN by Google One 4
map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]
VPN by Google One 4
map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]
VPN by Google One 4
map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]
VPN by Google One 4
time="2024-03-07T16:51:16.748118+08:00" level=warning msg="[TCP] dial dd [::1]:64988 --> ip.skk.moe:443 error: connect failed: interface not found\ninterface not found\nconnect failed: interface not found\ninterface not found"
map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]
```

只有两个接口留下来了

`map[Loopback Pseudo-Interface 1:0xc0000be280 以太网:0xc0000be230]`

**Comment by laggardkernel** [comment]
同一个问题 https://github.com/MetaCubeX/mihomo/issues/1031

相关 https://github.com/MetaCubeX/mihomo/issues/800

**Comment by wwqgtxx** [comment]
暂时撤销了产生影响的commit（https://github.com/MetaCubeX/mihomo/pull/601）
https://github.com/MetaCubeX/mihomo/commit/2e94531c72eca564ddbec268bf7760cfbca44428
不过不知道是否会导致hy1 faketcp回环的问题重现，有待进一步观察
