### ISSUE TITLE
【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！[Bug] 

### ISSUE THREAD

**Issue by linve-b** [MetaCubeX/mihomo#1318]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### System Version

0.46.014-beta

### Mihomo Version

【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！

### Configuration File

```yaml
【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
```

### Description

2024-06-12 02:42:37 【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
2024-06-12 02:42:37 【Meta】版本内核下载成功，开始更新...
2024-06-12 02:42:00 【Meta】版本内核正在下载，如下载失败请尝试手动下载并上传...
2024-06-12 02:40:18 守护程序：检测到转发规则顺序错误，修改插件防火墙规则...
2024-06-12 02:40:02 【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
2024-06-12 02:40:02 【Meta】版本内核下载成功，开始更新...
2024-06-12 02:39:53 【Meta】版本内核正在下载，如下载失败请尝试手动下载并上传...

### Reproduction Steps

2024-06-12 02:42:37 【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
2024-06-12 02:42:37 【Meta】版本内核下载成功，开始更新...
2024-06-12 02:42:00 【Meta】版本内核正在下载，如下载失败请尝试手动下载并上传...
2024-06-12 02:40:18 守护程序：检测到转发规则顺序错误，修改插件防火墙规则...
2024-06-12 02:40:02 【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
2024-06-12 02:40:02 【Meta】版本内核下载成功，开始更新...
2024-06-12 02:39:53 【Meta】版本内核正在下载，如下载失败请尝试手动下载并上传...
