### ISSUE TITLE
[Bug] clash meta for Android 应用包列表不能检测小米系统自带的app

### ISSUE THREAD

**Issue by shui-dun** [MetaCubeX/mihomo#1327]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

MIUI 14.0.6

### Mihomo Version

Clash Meta for
Android
2.10.1.Meta
Meta-Alpha-0c384b1-240
208

### Configuration File

```yaml
无
```

### Description

设置 > 网络 > 访问控制应用包列表 无法看到小米自带的app，例如应用商店 com.xiaomi.market，而clash for Android可以看到

### Reproduction Steps

打开 设置 > 网络 > 访问控制应用包列表 ，搜索应用商店

### Logs

```shell
手机上不方便看，应该和问题无关
```

**Comment by shui-dun** [comment]
能解释一下为什么invalid吗

**Comment by xishang0128** [comment]
@shui-dun https://github.com/MetaCubeX/mihomo/issues/1049
