### ISSUE TITLE
[Bug] notification issues in clash meta for android

### ISSUE THREAD

**Issue by fsheidaiee** [MetaCubeX/mihomo#1450]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

Android 14

### Mihomo Version

2.10.2 meta

### Configuration File

```yaml
mixed-port: 2090
allow-lan: true
ipv6: true
mode: Rule
log-level: info
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ./ui
external-ui-name: xd
global-client-fingerprint: firefox
sniffer:
  enable: true
  ## 对 redir-host 类型识别的流量进行强制嗅探
  ## 如：Tun、Redir 和 TProxy 并 DNS 为 redir-host 皆属于
  force-dns-mapping: false
  ## 对所有未获取到域名的流量进行强制嗅探
  # parse-pure-ip: true
  # 是否使用嗅探结果作为实际访问，默认 true
  # 全局配置，优先级低于 sniffer.sniff 实际配置
  override-destination: false
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    
    # 默认嗅探 80
    HTTP: # 需要嗅探的端口
      
      ports: [80, 8080-8880]
      # 可覆盖 sniffer.override-destination
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  endpoint-independent-nat: true
  dns-hijack:
    - 0.0.0.0:53
  auto-redirect: false
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  exclude-package:
   - com.v2ray.ang
dns:
  enable: true
  prefer-h3: false
  listen: 127.0.0.1:1053
  respect-rules: false
  ipv6: true
  default-nameserver:
    - 194.225.73.141
    - 185.97.117.187
    - 8.8.8.8
    - system
  enhanced-mode: fake-ip # or redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 'https://dns.quad9.net/dns-query#🔰Select'
    - '9.9.9.9#🔰Select'
  proxy-server-nameserver:
   - '8.8.8.8#DIRECT'
   - '5.200.200.200#DIRECT'
   - '1.1.1.1#DIRECT'
  nameserver-policy:
      "rule-set:ads-all": rcode://success
      "rule-set:private": dhcp://system
      "+.ir": [dhcp://system, 8.8.8.8, 5.200.200.200]
      "rule-set:ir": [dhcp://system, 8.8.8.8, 5.200.200.200]
```

### Description

Hi
In clash meta for android
Almost all notifications are stopped when connecting.
I have to open each app to have notifications.
Whats the problem?

### Reproduction Steps

Ruuning the config in clash meta for android

**Comment by xishang0128** [comment]
https://github.com/MetaCubeX/mihomo/issues/1049

**Comment by 1Megabyte** [comment]
Did you manage to find a solution for this issue?

**Comment by fsheidaiee** [comment]
> Did you manage to find a solution for this issue?

no not resolved yet even with the new versions
