### ISSUE TITLE
[Bug] yacd-meta proxies tab is empty with latest alpha 

### ISSUE THREAD

**Issue by remedynotavailable** [MetaCubeX/mihomo#930]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-b632575

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
any
```

### Mihomo log

No log but there's error messages in browser's console.

```shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at index-aaeb651e.js:104:30997
```

### Description

I checked the network tab in the browser. Mihomo api reply on `/providers/proxies` with history: null which is not the case with the previous version.

```json
{
  "providers": {
    "default": {
      "expectedStatus": "*",
      "name": "default",
      "proxies": [
        {
          "alive": true,
          "extra": {},
          "history": null,
          "id": "1eea14a0-0400-6ebf-9984-6ef57f34e24c",
          "name": "DIRECT",
          "tfo": false,
          "type": "Direct",
          "udp": true,
          "xudp": false
        },
        {
          "alive": true,
          "extra": {},
          "history": null,
          "id": "1eea14a0-0403-630e-9984-db4f718acd50",
          "name": "REJECT",
          "tfo": false,
          "type": "Reject",
          "udp": true,
          "xudp": false
        },
...
```

I guess it's related to #860

**Comment by lux5am** [comment]
Okay it's working fine now. Thank you sirs.
